version: "3.7"

services:
  web:
    build:
      context: .
      target: web
    command: npm run dev
    environment:
      NODE_ENV: "development"
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/web
      - /usr/src/web/node_modules
      - /usr/src/web/.next

